version: '3.8'

services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "1243:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html:ro
    networks:
      - vita
    depends_on:
      - php
    restart: unless-stopped

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./www:/var/local/sandboxes/dev/www
    environment:
      - PHP_FPM_LISTEN=0.0.0.0:9000
    networks:
      - vita
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vita
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  vita:
    driver: bridge
